core/module/Profile/lang/profile_de.php
Here, have a PR, because you don't have enough todo :)
Fixes some typos in german translation of the _places_ thing in the profile section
=> Wechall: Typo fixes for german 'places'

core/module/Dog/dog_plugins/dog_plugin/Auth/facein_Pb.php
Fix a typo in the english translation of the .facein Lamb/Dog plugin
=> Lamb3: Fix typo in english .facein translation

www/tpl/default/module/WeChall/wcfootermenu.php
That link used to go to `/changes.txt`, but that file got replaced by SVN,
and later by github. So why not just directly link to the github commit
log?
=> Wechall: Fix that changes link which is broken since ages

core/module/Dog/dog_modules/dog_module/Shadowlamb/lang/shadowlamb_de.php, core/module/Dog/dog_modules/dog_module/Shadowlamb/lang/shadowlamb_en.php, core/module/Dog/dog_modules/dog_module/Shadowlamb/lang/shadowlamb_es.php, core/module/Dog/dog_modules/dog_module/Shadowlamb/lang/shadowlamb_fr.php, core/module/Dog/dog_modules/dog_module/Shadowlamb/lang/shadowlamb_it.php, core/module/Dog/dog_modules/dog_module/Shadowlamb/lang/shadowlamb_lv.php
The shadowlamb language file had duplicate array keys for `mount`
=> Fix duplicate array keys in lang file

www/tpl/wc4/css/wechall4.css
The chall_head element, showing the challenge meta data at the top,
rendered an ugly scrollbar (at least in chromium). To remove that the
height of the element is set to line-height + 1
=> [Wechall] Fix ugly chall_head scrollbar

core/module/PM/method/Delete.php
On PM deletion attempts with an invalid `token` parameter, the correct
token got echoed to the page.
=> Do not echo invalid PM deletion tokens

core/module/WeChall/method/LinkedSites.php
The sorting on the linked sites overview page did not sort properly by
the _solved_ column. The sort parameter used there `regat_challsolved`,
was not whitelisted in the sorting fields.
Fixes issue #39
=> [Wechall] Fix sorting of linked_sited by solved count

core/module/Dog/dog_modules/dog_module/Shadowlamb/cmd/info/motd.php
* The path to the shadowlamb `#motd` command was wrong, it repeated the
module path twice.
* Fixed full path disclosure: When unable to read the motd file, the
full path to it's supposed location was disclosed
* Remove error-suppression operator: The only case when this might be
possibly relevant is when the file is not readable, the PHP doc states
it "generates a WARNING" in that case. Added the `is_readable` check to
resolve this.
* Return early on not-found motd file. This avoids Having a message
`Message of the day: ` after the error message
Fixes issue #21
=> [Shadowlamb] Fix motd path

core/module/Dog/dog_modules/dog_module/Shadowlamb/spell/freeze.php, core/module/Dog/dog_modules/dog_module/Shadowlamb/spell/icedorn.php
This _should_ fix the problems with freeze/icedorn spells, as mentioned in #3 e.g.
Need a Shadowlamb pro coder to approve.
=> fix busy time applied is 10 x time of effect

core/inc/install/GWF_AutoConfig.php, core/inc/install/GWF_InstallConfig.php, www/challenge/warchall/live_lfi/www/live_lfi.config.php, www/challenge/warchall/live_rfi/www/live_rfi.config.php, www/install/config.example.php, www/protected/config.example.php
On PHP >= 8.0 (?? unverified, might be >=7.2 as well), when on a 32 bit
PHP installation, 0xffffffff is too big for a signed integer. Therefore,
it is casted to a float, which then dies due to a `TypeError` when passed
to `error_reporting()`, which expects `int`.
Either way, `0xffffffff` is a bad choice here:
* it relies on undocumented/internal behavior
* a named constant is always nicer
Sorry for these whitespace fixes, my IDE auto-added them :D
=> Fix error_reporting config for 32 bit systems

www/challenge/christmas2021/grampa/lang/chall_en.php
The link tag was not closed, causing even focusing on the input field to open the link target.
=> Fix `2021 Christmas Grampa` link

core/inc/util/GWF_Crypt.php, core/inc/util/GWF_Numeric.php, core/inc/util/GWF_StringPermutation.php, core/module/Dog/lamb_module/PG/Mod_PG.php, www/challenge/hashgame/hg_wc4.php, www/challenge/noother/php0818/php0818.php, www/challenge/training/crypto/caesar/index.php, www/challenge/training/crypto/caesar2/index.php, www/challenge/training/crypto/digraph/index.php, www/challenge/training/crypto/simplesub1/index.php, www/challenge/training/crypto/simplesub2/index.php, www/challenge/training/crypto/transposition1/index.php, www/challenge/training/encodings/ascii/index.php, www/challenge/training/encodings/bacon2/index.php, www/challenge/training/encodings/url/index.php
Curly braces for accessing string or array offsets have been deprecated since PHP 7.4, and removed in PHP 8.0.
See: https://www.php.net/manual/en/migration80.incompatible.php#migration80.incompatible.core.other
=> Replace deprecated curly brace syntax

core/module/Dog/dog_include/Dog_WorkerThread.php, core/module/Dog/dog_modules/dog_module/Shadowlamb/core/ai/SR_NPCBase.php
Writing to properties which don't exist is no longer supported in PHP 8.2.
Defined them.
=> Dog: Define undefined properties

core/module/Dog/dog_timer/all_servers_one/timers/infinity/30/solvers_wix.php
The site is dead, this uselessly polls some non-existing URL and spams the log.
=> Remove wixxerd.com solved-announcement poller

core/module/Dog/dog_plugins/dog_plugin/Data/weather_Pb.php
Example:
> livinskull: .help weather
> dog: livinskull: Usage: .weather <some location>. Get weather information by location name or zipcode. Provided by wttr.in. This works everywhere and requires Public permissions. <livinskull> .weather Munich
> dog: livinskull: Munich: ☀️   +8°C
> livinskull: .weather Texas
> dog: livinskull: Texas: ☁️   +17°C
> livinskull: .weather станция Восток
> dog: livinskull: станция Восток: ☁️   -40°C
=> Dog: Replace defunct google weather

core/module/WeChall/method/LinkedSites.php
This fixes a crash on linking a new site, when working with MySql 8 and its default settings:
```
12:31 [172.20.0.1:admin] - GDO Error(1364): Field 'regat_lastdate' doesn't have a default value
INSERT INTO `gwf3_wc_regat` (`regat_uid`,`regat_sid`,`regat_onsitename`,`regat_onsitescore`,`regat_challcount`,`regat_options`,`regat_langid`,`regat_tagbits`,`regat_linkdate`) VALUES ('3','1','admin','0','0','0','1','15','20240616')
```
Leaving the `regat_lastdate` column undefined on INSERT errors with MySql 8 due to the column not having a default value.
Since the date logic is custom, and might not work with NULL, and I don't have any idea how to do DB migrations in this, the simplest solution is to set it to the same value as the link date. That's not logically wrong either.
It _is_ a behavior …
=> Set *last updated* date of a site to the *link date* on link

www/challenge/identity/stalking/index.php
If you visit the `Stalking` challenge without having solved the `Identity` challenge before, or are just not logged in, the error message rendered is:
> Please solve the %s challenge first.
Other usages of the `$chall->lang()` indicate an array there, so this _might_ fix it (untested).
=> WeChall: Fix non-replaced placeholder in Stalking error message

core/module/WeChall/Module_WeChall.php, core/module/WeChall/lang/wechall/_wc_cs.php, core/module/WeChall/lang/wechall/_wc_de.php, core/module/WeChall/lang/wechall/_wc_en.php, core/module/WeChall/lang/wechall/_wc_es.php, core/module/WeChall/lang/wechall/_wc_fr.php, core/module/WeChall/lang/wechall/_wc_hu.php, core/module/WeChall/lang/wechall/_wc_it.php, core/module/WeChall/lang/wechall/_wc_ru.php, core/module/WeChall/lang/wechall/_wc_sr.php
- Fix typo in `tommorow`
- added translations for it (de/en/es/fr manual, rest is deepl-provided translations)
- also fixed duplicate `yesterday` key in translations
=> Fix typo in wechall birthdays module

core/module/WeChall/lang/wechall/_wc_cs.php, core/module/WeChall/lang/wechall/_wc_de.php, core/module/WeChall/lang/wechall/_wc_en.php, core/module/WeChall/lang/wechall/_wc_es.php, core/module/WeChall/lang/wechall/_wc_fr.php, core/module/WeChall/lang/wechall/_wc_hu.php, core/module/WeChall/lang/wechall/_wc_it.php, core/module/WeChall/lang/wechall/_wc_ru.php, core/module/WeChall/lang/wechall/_wc_sr.php
wechall: Add missing translations for `th_no_email`
This is a setting name in the `Edit Site` Form:
=> wechall: Add missing translations for `th_no_email`

core/module/Dog/dog_modules/dog_module/Shadowlamb/city/Seattle/quest/Seattle_Farmer.php, core/module/Dog/dog_modules/dog_module/Shadowlamb/city/Vegas/quest/Vegas_DarkBonds.php, core/module/Dog/dog_modules/dog_module/Shadowlamb/city/Vegas/quest/Vegas_HiJack.php, core/module/Dog/dog_modules/dog_module/Shadowlamb/city/Vegas/quest/Vegas_Ringdom.php
A few `lang()` calls are missing `array` wrappers when used with a single argument, this should fix all of them.
Example of current output:
```
#talk 1
Joe says: "Please, protect my sheep! You still need to kill %s more MonsterWerewolfs!"
```
P.S. It is ironic to see [incorrect usage](https://github.com/gizmore/gwf3/blob/b1512aabfc28476f77daa05eb774fadfbf7804fa/core/module/Dog/dog_modules/dog_module/Shadowlamb/city/Vegas/quest/Vegas_DarkBonds.php#L24) just a few lines below [the correct one](https://github.com/gizmore/gwf3/blob/b1512aabfc28476f77daa05eb774fadfbf7804fa/core/module/Dog/dog_modules/dog_module/Shadowlamb/city/Vegas/quest/Vegas_DarkBonds.php#L13).
=> Shadowlamb: Fix quest-related single-vararg i18n calls

core/module/WeChall/WC_Warbox.php
Fixing error on page https://www.wechall.net/en/challenge/Mawekl/what_is_your_name/who.php :  
```
Parse error: syntax error, unexpected ':', expecting ';' or '{' in /home/wechall/www/wc5/core/module/WeChall/WC_Warbox.php on line 48
PHP Fatal Error(1): syntax error, unexpected ':', expecting ';' or '{' in core/module/WeChall/WC_Warbox.php line 48
```
=> Fix method return type error impacting What is your name challenge
